### ISSUE TITLE
display error on hide/show

### ISSUE THREAD

**Issue by coooooooooorey** [leafcode/libsleek#1]
int main(int argc, char *argv[])
{
    QApplication a(argc, argv);

    QFile stylesheet( ":/themes/graphite.css" );
    if ( stylesheet.open( QFile::ReadOnly ) ) {
        QString styleSheet = stylesheet.readAll();
        a.setStyleSheet( styleSheet );
        stylesheet.close();
    }

    TestWindow testW(true);
    testW.show();

    QTimer t;
    t.connect(&t,&QTimer::timeout,[&](){
        testW.isVisible()
                ? testW.hide()
                  : testW.show();
    });
    t.start(2000);

    return a.exec();
}

**Comment by coooooooooorey** [comment]
QTimer t;
t.connect(&t,&QTimer::timeout,[&](){
    testW.isVisible()
            ? testW.hide()
              : testW.show();
});
t.start(2000);

this is what I  add. 

Sometimes  it doesn't display correctly.

**Comment by martinmolin** [comment]
I assume that you're running Windows, I'll investigate this after work!
